const fs = require('fs');
const path = require('path');
const prisma = require('../../config/db');
const { BILLING_WARNING_THRESHOLD_DAYS } = require('../../config/billing');
const { getDaysRemaining } = require('../../utils/billing');

function submissionDTO(row) { return { id: row.id, plan: row.plan ? { id: row.plan.id, name: row.plan.name, price: row.plan.price, billingCycle: row.plan.billing_cycle } : undefined, payoutMethod: row.payout_method ? { id: row.payout_method.id, label: row.payout_method.label, type: row.payout_method.type } : undefined, amount: row.amount, referenceNote: row.reference_note, screenshotUrl: row.screenshot_url, status: row.status, rejectionReason: row.rejection_reason, reviewedAt: row.reviewed_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
function removeProof(url) { if (!url) return; const file = path.join(__dirname, '..', '..', '..', 'uploads', 'payment-proofs', path.basename(url)); if (fs.existsSync(file)) fs.unlinkSync(file); }

class BillingService {
  async getSubscription() { const row = await prisma.subscription.findUnique({ where: { business_id: prisma.getCurrentBusinessId() }, include: { plan: true } }); if (!row) { const error = new Error('Subscription not found'); error.status = 404; throw error; } return { plan: { id: row.plan.id, name: row.plan.name, price: row.plan.price, billingCycle: row.plan.billing_cycle }, status: row.status, currentPeriodStart: row.current_period_start, currentPeriodEnd: row.current_period_end, daysRemaining: getDaysRemaining(row.current_period_end), warningThresholdDays: BILLING_WARNING_THRESHOLD_DAYS }; }
  async listPlans() { return (await prisma.basePrisma.plan.findMany({ where: { is_active: true }, orderBy: { price: 'asc' } })).map((plan) => ({ id: plan.id, name: plan.name, price: plan.price, billingCycle: plan.billing_cycle, trialPeriodDays: plan.trial_period_days, defaultEnabledModules: plan.default_enabled_modules, defaultMaxAdminSeats: plan.default_max_admin_seats })); }
  async listPayoutMethods() { return (await prisma.basePrisma.payoutMethod.findMany({ where: { is_active: true }, orderBy: { label: 'asc' } })).map((method) => ({ id: method.id, label: method.label, type: method.type, accountTitle: method.account_title, accountNumber: method.account_number, instructions: method.instructions })); }
  async listSubmissions() { return (await prisma.paymentSubmission.findMany({ include: { plan: true, payout_method: true }, orderBy: { created_at: 'desc' } })).map(submissionDTO); }
  async validateInput(data) { const [plan, payout] = await Promise.all([prisma.basePrisma.plan.findFirst({ where: { id: data.planId, is_active: true } }), prisma.basePrisma.payoutMethod.findFirst({ where: { id: data.payoutMethodId, is_active: true } })]); if (!plan || !payout || Number(data.amount) <= 0) { const error = new Error('Choose an active plan and payout method, and enter a positive amount'); error.status = 400; throw error; } }
  async create(data, userId, file) { if (!file) { const error = new Error('Payment screenshot is required'); error.status = 400; throw error; } try { await this.validateInput(data); const pending = await prisma.paymentSubmission.findFirst({ where: { status: 'PENDING' } }); if (pending) { const error = new Error('A payment submission is already pending review. Edit it instead.'); error.status = 409; throw error; } return submissionDTO(await prisma.paymentSubmission.create({ data: { plan_id: data.planId, payout_method_id: data.payoutMethodId, submitted_by: userId, amount: Number(data.amount), reference_note: data.referenceNote?.trim() || null, screenshot_url: `/uploads/payment-proofs/${file.filename}` }, include: { plan: true, payout_method: true } })); } catch (error) { removeProof(`/uploads/payment-proofs/${file.filename}`); throw error; } }
  async update(id, data, file) { const row = await prisma.paymentSubmission.findFirst({ where: { id } }); if (!row) { const error = new Error('Payment submission not found'); error.status = 404; throw error; } if (row.status === 'APPROVED') { const error = new Error('Approved payment submissions cannot be edited'); error.status = 403; throw error; } try { await this.validateInput(data); const nextUrl = file ? `/uploads/payment-proofs/${file.filename}` : row.screenshot_url; const updated = await prisma.paymentSubmission.update({ where: { id }, data: { plan_id: data.planId, payout_method_id: data.payoutMethodId, amount: Number(data.amount), reference_note: data.referenceNote?.trim() || null, screenshot_url: nextUrl, status: 'PENDING', rejection_reason: null, reviewed_by: null, reviewed_at: null }, include: { plan: true, payout_method: true } }); if (file) removeProof(row.screenshot_url); return submissionDTO(updated); } catch (error) { if (file) removeProof(`/uploads/payment-proofs/${file.filename}`); throw error; } }
}
module.exports = new BillingService();
