const prisma = require('../../config/db'); const { computeNewPeriodEnd } = require('../../utils/billing');
class PaymentSubmissionsService {
  toDTO(row) { return { id: row.id, business: row.business ? { id: row.business.id, name: row.business.name, slug: row.business.slug } : undefined, plan: row.plan ? { id: row.plan.id, name: row.plan.name, price: row.plan.price, billingCycle: row.plan.billing_cycle } : undefined, payoutMethod: row.payout_method ? { id: row.payout_method.id, label: row.payout_method.label } : undefined, amount: row.amount, referenceNote: row.reference_note, screenshotUrl: row.screenshot_url, status: row.status, rejectionReason: row.rejection_reason, reviewedAt: row.reviewed_at, createdAt: row.created_at }; }
  include() { return { business: true, plan: true, payout_method: true, submittedByUser: { select: { name: true, email: true } }, reviewedByAdmin: { select: { name: true, email: true } } }; }
  async list({ status, businessId }) { const where = { ...(status ? { status } : {}), ...(businessId ? { business_id: businessId } : {}) }; return (await prisma.basePrisma.paymentSubmission.findMany({ where, include: this.include(), orderBy: { created_at: 'desc' } })).map((row) => this.toDTO(row)); }
  async approve(id, platformAdminId) { return prisma.basePrisma.$transaction(async (tx) => { const submission = await tx.paymentSubmission.findUnique({ where: { id }, include: { plan: true } }); if (!submission) { const error = new Error('Payment submission not found'); error.status = 404; throw error; } if (submission.status !== 'PENDING') { const error = new Error('Only pending payment submissions can be approved'); error.status = 409; throw error; } const subscription = await tx.subscription.findUnique({ where: { business_id: submission.business_id } }); if (!subscription) { const error = new Error('Subscription not found'); error.status = 404; throw error; } const now = new Date(); const periodEnd = computeNewPeriodEnd({ now, currentPeriodEnd: subscription.current_period_end, subscriptionStatus: subscription.status, billingCycle: submission.plan.billing_cycle }); await tx.subscription.update({ where: { id: subscription.id }, data: { plan_id: submission.plan_id, status: 'ACTIVE', current_period_start: now, current_period_end: periodEnd } }); await tx.business.update({ where: { id: submission.business_id }, data: { status: 'ACTIVE', enabled_modules: submission.plan.default_enabled_modules, max_admin_seats: submission.plan.default_max_admin_seats } }); const reviewed = await tx.paymentSubmission.update({ where: { id }, data: { status: 'APPROVED', reviewed_by: platformAdminId, reviewed_at: now, rejection_reason: null }, include: this.include() }); await tx.platformAuditLog.create({ data: { platform_admin_id: platformAdminId, action: 'APPROVED_PAYMENT_SUBMISSION', target_business_id: submission.business_id, changes: { paymentSubmissionId: id, planId: submission.plan_id, currentPeriodEnd: periodEnd.toISOString() } } }); return this.toDTO(reviewed); }); }
  async reject(id, reason, platformAdminId) { if (!reason?.trim()) { const error = new Error('A rejection reason is required'); error.status = 400; throw error; } const row = await prisma.basePrisma.paymentSubmission.update({ where: { id }, data: { status: 'REJECTED', rejection_reason: reason.trim(), reviewed_by: platformAdminId, reviewed_at: new Date() }, include: this.include() }); return this.toDTO(row); }
}
module.exports = new PaymentSubmissionsService();
